# GitHub Sponsors - Suporte o desenvolvimento de Askesis
# https://github.com/sponsors/farifran

github: farifran
custom:
  - "https://www.buymeacoffee.com/askesis"
  - "https://ko-fi.com/askesis"

# Outras opções (descomentar se adicionar):
# patreon: askesis
# liberapay: askesis
# open_collective: askesis
